In [1]:
import pandas as pd

from preprocessing_kit.preprocessing.data_processor import DataProcessor
from preprocessing_kit.preprocessing.processor import Processor

In [2]:
df_init = pd.read_csv("../data/bank-additional-full.csv", sep=';')
df = df_init.copy()
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [3]:
processor = Processor(target_col="y", unnecessary_columns=["duration"], scaling_method="standard")
data_processor = DataProcessor(
    processor=processor,
    apply_outliers_processing=True,
    apply_feature_engineering=True
)

X_train, y_train, X_val, y_val = data_processor.process(df)

In [4]:
display(X_train.head(1)), display(X_val.head(1))

,age,education,contact,month,day_of_week,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,...,marital_single,housing_no,housing_yes,loan_no,loan_yes,default_no,default_yes,poutcome_failure,poutcome_nonexistent,poutcome_success
25611,0.89007,3.0,1,11,3,1.174958,-0.376437,-0.114858,-0.648967,-0.324914,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

,age,education,contact,month,day_of_week,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,...,marital_single,housing_no,housing_yes,loan_no,loan_yes,default_no,default_yes,poutcome_failure,poutcome_nonexistent,poutcome_success
14455,-0.78599,6.0,1,7,2,1.594231,-0.376437,0.8398,0.590675,-0.476655,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

(None, None)