In [1]:
import json
import pandas as pd

from configuration.configuration import EncoderConfig, Configuration
from preprocessing_kit.preprocessing.data_processor import DataProcessor
from preprocessing_kit.preprocessing.processor import Processor

%load_ext autoreload
%autoreload 2

In [2]:
df_init = pd.read_csv("../data/bank-additional-full.csv", sep=';')
df = df_init.copy()
df.head(3)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
with open("../config.json") as f:
    raw = json.load(f)

configuration = Configuration(
    encoding_config=EncoderConfig(**raw["encoder"]),
    outlier_config=raw["outlier_config"],
    missing_values=raw["missing_values"],
    feature_engineering=raw["feature_engineering"]
)

In [4]:
processor = Processor(target_col="y", unnecessary_columns=["duration"], scaling_method="standard", config=configuration)
data_processor = DataProcessor(
    processor=processor,
    apply_outliers_processing=True,
    apply_feature_engineering=True,
    config=configuration
)

X_train, y_train, X_val, y_val = data_processor.process(df)

In [5]:
display(X_train.head(1)), display(X_val.head(1))

,age,education,contact,month,day_of_week,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,...,housing_yes,loan_no,loan_unknown,loan_yes,default_no,default_unknown,default_yes,poutcome_failure,poutcome_nonexistent,poutcome_success
25611,0.89007,3.0,1,NaN,NaN,1.174958,-0.350127,-0.114858,-0.648967,-0.322269,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

,age,education,contact,month,day_of_week,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,...,housing_yes,loan_no,loan_unknown,loan_yes,default_no,default_unknown,default_yes,poutcome_failure,poutcome_nonexistent,poutcome_success
14455,-0.78599,6.0,1,NaN,2.0,1.594231,-0.350127,0.8398,0.590675,-0.473517,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

(None, None)